plugin: s1_geomad.plugin.S1GeoMAD
product:
  name: csiro_s1_mosaic_annual
  short_name: csiro_s1_mosaic_annual
  version: 0.1.0
  product_family: Sentinel-1
  explorer_path: explorer.csiro.easi-eo.solutions
  region_code_format: "x{x:03d}y{y:03d}"
  producer: csiro
plugin_config:
  chunks:
    longitude: 2000
    latitude: 2000
  geomad_work_chunks: [600, 600]
max_processing_time: 600
s3_acl: bucket-owner-full-control
