plugin: s1_geomad.plugin.S1GeoMAD
product:
  name: csiro_s1_mosaic_annual
  short_name: csiro_s1_mosaic_annual
  version: 0.1.0
  product_family: Sentinel-1
  collections_site: explorer.csiro.easi-eo.solutions
  region_code_format: "x{x:03d}y{y:03d}"
max_processing_time: 600
s3_acl: bucket-owner-full-control
