kind: Workflow

metadata:
  generateName: s1-geomad-
  namespace: csa-sar-capability-argo

spec:
  entrypoint: workflow-entrypoint
  # serviceAccountName: csa-sar-capability-sa-argo
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 600s
  nodeSelector:
    nodegroup: data_pipelines
  tolerations:
    - key: easi.csiro.au/dedicated
      operator: Equal
      effect: NoSchedule
      value: data_pipelines
  parallelism: 1
  arguments:
    parameters:
      - name: image-name
        value: "ghcr.io/auspatious/csiro-sar-exploration" # The Docker image
      - name: image-tag
        value: "0.0.0" # The Docker image and code version
      - name: version
        value: "0.0.0" # The version of the data product being made
      - name: output-bucket
        value: easi-csiro-dc-data-projects # The bucket where the data will be stored
      - name: output-prefix
        value: sar # The prefix of the path where the data will be stored
      - name: temporal-range
        value: "2023--P1Y"
      - name: frequency
        value: "annual"
      - name: grid
        value: "au-30"
      - name: overwrite
        value: "--no-overwrite" # Can be "--overwrite" or "--no-overwrite"
  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: test-process
            template: test-process
            arguments:
              parameters:
                - name: temporal-range
                  value: "{{ workflow.parameters.temporal-range }}"
                - name: frequency
                  value: "{{ workflow.parameters.frequency }}"
                - name: grid
                  value: "{{ workflow.parameters.grid }}"
                - name: input-product
                  value: "sentinel1_grd_gamma0_beta"

    - name: test-process
      inputs:
        parameters:
          - name: temporal-range
          - name: frequency
          - name: grid
          - name: input-product
          - name: config
            value: |
              plugin: s1_geomad.plugin.S1Mosaic
              plugin_config:
                chunks:
                  longitude: 2048
                  latitude: 2048
              product:
                name: csiro_s1_mosaic
                short_name: csiro_s1_mosaic
                product_family: gamma0
                producer: csiro.au
                version: 0.0.1
                collections_site: explorer.csiro.easi-eo.solutions
                region_code_format: "x{x:03d}y{y:03d}"
              max_processing_time: 600
              s3_acl: bucket-owner-full-control
              aws_unsigned: false

      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 100Mi
            cpu: 1.0
        env:
          - name: DB_PASSWORD
            value: "SECRET"
          - name: DB_HOSTNAME
            value: "v2-db-easihub-csiro-eks.cluster-ro-cvaedcg0qvwd.ap-southeast-2.rds.amazonaws.com"
          - name: DB_USERNAME
            value: "easi_db_user"
          - name: DB_DATABASE
            value: "easihub_csiro_db"

        # volumeMounts:
        #   - name: user-secret-easi-odc-v2
        #     mountPath: "/root/.user-secret-easi-odc-v2"
        #     readOnly: true
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            set -e

            cd /tmp

            echo "Preparing DB..."
            odc-stats save-tasks \
              --temporal-range="{{inputs.parameters.temporal-range}}" \
              --frequency="{{inputs.parameters.frequency}}" \
              --grid="{{inputs.parameters.grid}}" \
              --input-products={{inputs.parameters.input-product}} \
              job.db

            odc-stats run \
              --config="{{ inputs.parameters.config }}" \
              --resolution="30" \
              --threads="16" \
              --memory-limit="10GB" \
              --location="file:///tmp/s1_geomad/output" \
              job.db \
              "2023--P1Y,40,6"

            ls -lah /tmp/s1_geomad/output/
